FROM node:16-alpine as builder

WORKDIR /usr/alura-tracker/app

COPY package.json .

RUN yarn install

COPY . .

RUN yarn build

FROM node:16-alpine

WORKDIR /usr/alura-tracker/app

RUN apk add --no-cache bash 

COPY --from=builder /usr/alura-tracker/app/node_modules ./node_modules
COPY --from=builder /usr/alura-tracker/app/dist ./dist

RUN npm i -g serve

USER node

EXPOSE 3000

ENTRYPOINT [ "serve", "-s", "dist" ]